Refactor one
Noctis-Dev/leaf-founding pull request #6
Opened 2024-05-12 20:50 UTC by Mane-jaker

Se elimino todo lo inecesario para el flujo de crear proyecto, y ya existe la funcionalidad para agregar o quitar milestones, tengo dudas si el manage, tambien se quitaria o que continue en el proyecto

2024-05-15 03:57 UTC, JBunCE requested changes
Parece que todo esta en orden, madamas arregla el comentario que te deje y ya te doy el aproval

2024-05-15 03:57 UTC, JBunCE commented on src/components/FormCreate/Milestone.tsx
> +}
Elementos mal formateados

2024-05-16 18:35 UTC, Mane-jaker commented on src/components/FormCreate/Milestone.tsx
> +}
you can check my new changes

2024-05-16 23:39 UTC, JBunCE approved these changes

2024-05-16 23:39 UTC, merged